name: Github Release

#on:
#  push:
#    tags:
#      - 'v*.*.*'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
          go-version: '1.22.2'

      - name: Install GH cli
        run: |
          GH_CLI_VERSION="2.49.2"
          # Download the GitHub CLI tarball for the specified version
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y))
          wget https://github.com/cli/cli/releases/download/v$GH_CLI_VERSION/gh_${GH_CLI_VERSION}_linux_amd64.tar.gz
          # Extract the tarball
          tar -xzf gh_${GH_CLI_VERSION}_linux_amd64.tar.gz
          # Move the binaries to /usr/local/bin
          sudo mv gh_${GH_CLI_VERSION}_linux_amd64/bin/gh /usr/local/bin/
          # Verify the installation
          gh --version

      - name: Build
        run: |
          go version
          go build -o f1-telemetry
          env GOOS=windows GOARCH=amd64 go build -o f1-telemetry.exe

      - name: Archive binary
        run: |
          tar czf f1-telemetry.tar.gz f1-telemetry
          zip f1-telemetry.zip f1-telemetry.exe

      - name: Create Release
        id: create_release
        run: |
          RELEASE_URL=$(gh release create "$(echo "v0.0.1")" -t "Test release" --notes "$(echo "lorem ipsum")")
          echo "release_url=$RELEASE_URL" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        run: |
          gh release upload v0.0.1 f1-telemetry.tar.gz

#
#      - name: Set Release
#        run: |
#          RELEASE_BODY="lorem ipsum dolor"
#          TAG="testtag"
#          RELEASE_TITLE="Release test"
#
#          gh release create "$(echo "$TAG")" -t "📦 ${RELEASE_TITLE}" --notes "$(echo "$RELEASE_BODY")"
