name: Github Release

on:
  workflow_dispatch:

jobs:
  generate-release:
    runs-on: ubuntu@latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
          go-version: '1.22.2'
      - run: go version
      - run: |
          GH_CLI_VERSION="2.49.2"
          # Download the GitHub CLI tarball for the specified version
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y))
          wget https://github.com/cli/cli/releases/download/v$GH_CLI_VERSION/gh_${GH_CLI_VERSION}_linux_amd64.tar.gz
          # Extract the tarball
          tar -xzf gh_${GH_CLI_VERSION}_linux_amd64.tar.gz
          # Move the binaries to /usr/local/bin
          sudo mv gh_${GH_CLI_VERSION}_linux_amd64/bin/gh /usr/local/bin/
          # Verify the installation
          gh --version
      - run: go build main.go
        

#      - name: Set Release
#        run: |
#          RELEASE_BODY="lorem ipsum dolor"
#          TAG="testtag"
#          RELEASE_TITLE="Release test"
#
#          gh release create "$(echo "$TAG")" -t "📦 ${RELEASE_TITLE}" --notes "$(echo "$RELEASE_BODY")"
